### ISSUE TITLE
RMSE和MAE问题

### ISSUE THREAD

**Issue by joe17maker** [lijunxian111/UIGNN#1]
![屏幕截图 2024-04-27 024826](https://github.com/lijunxian111/UIGNN/assets/65492300/9eee54b9-c212-4ba1-9f35-864c4bf66310)

**Comment by joe17maker** [comment]
![屏幕截图 2024-04-27 024931](https://github.com/lijunxian111/UIGNN/assets/65492300/ecbeedb6-4c9c-47b1-8399-eea36afd3351)
貌似RMSE和MAE的值搞反了，而一般也确实是RMSE的值更大。

**Comment by qishenzhou** [comment]
![image](https://github.com/lijunxian111/UIGNN/assets/44823778/a0b55722-4bd6-497e-9f24-3c68151a6fd5)
![image](https://github.com/lijunxian111/UIGNN/assets/44823778/87f73546-ee51-411d-a019-9850932bf06b)

R^2计算也有问题，其他指标计算的时候都把mask部分元素排除了，但R^2没有。并且，为方便计算指标，预测值和真实值都乘以了test_mask（0 1矩阵）,相当于需要遮盖的部分两者被强行统一了。这导致R^2数值大幅提升。

**Comment by lijunxian111** [comment]
> ![屏幕截图 2024-04-27 024931](https://private-user-images.githubusercontent.com/65492300/326081131-ecbeedb6-4c9c-47b1-8399-eea36afd3351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDE3NTMsIm5iZiI6MTczNTA0MTQ1MywicGF0aCI6Ii82NTQ5MjMwMC8zMjYwODExMzEtZWNiZWVkYjYtNGM5Yy00N2IxLTgzOTktZWVhMzZhZmQzMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDExNTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjZjNjg3NDU0OTk5OGRlNzA2NTE4NDM5MWIxMjNkMzJjNDUxNDQwZTM0M2EwYWYyN2QwOTMxNWNlMDhiYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pEv0WJ1loC2uI1YJg3JBuFxNZiB0XU1Le2FhqkHA9zs) 貌似RMSE和MAE的值搞反了，而一般也确实是RMSE的值更大。

Thank you for pointing this out. We make sure that our results are truly recorded, (the headlines of our table in the paper face some bugs, and we will modify that in the Arxiv version.)
